Repository FESI9-4/FE, pull requests merged in 2025-06, with the labels that each got.

#68 [NO ISSSUES] provider fix
  src/app/layout.tsx
  src/assets/index.ts
  src/components/providers/QueryProvider.tsx
Labels: fix

#94 [#93] JEST 설정 추가
  jest.config.ts
  jest.setup.ts
  package-lock.json
  package.json
  src/__test__/test.ts
  src/components/main/TabSection.tsx
Labels: chore

#107 [#106] 404 페이지 구현
  src/app/not-found.tsx
Labels: page

#121 [NO ISSEU] toast 스타일링
  src/app/globals.css
  src/app/layout.tsx
Labels: feat, layout

#129 [#128] 회원가입 프록시 삭제
  src/mocks/handlers/auths.ts
  src/utils/apis/authApi.ts
  src/utils/apis/clientFetcher.ts
  src/utils/apis/fetchInstance.ts
Labels: refactor, api

#139 [#138] 로그인/회원가입/비밀번호 찾기 버튼 중복 클릭 방지
  src/app/globals.css
  src/components/auth/FindPasswordForm.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/SignupForm.tsx
  src/mocks/index.ts
Labels: refactor, fix

#142 [#141] 팬팔 참여하기/취소하기 동기화 문제 해결 refetch
  src/components/detailPage/DetailPageCard.tsx
  src/components/detailPage/DetailPageParticipation.tsx
  src/components/ui/CardList.tsx
  src/components/ui/ContainerInformation.tsx
  src/components/ui/ContainerProgress.tsx
  src/components/ui/ProgressChip.tsx
  src/hooks/queries/useFanFalMutations.ts
  src/mocks/index.ts
  src/types/card.ts
Labels: fix, api

#144 [NO ISSUE] 코드 정리
  src/__mock__/user.ts
  src/app/api/proxy/login/route.ts
  src/app/api/proxy/refresh/route.ts
  src/app/page.tsx
  src/app/wishlist/page.tsx
  src/components/auth/FindPasswordForm.tsx
  src/components/detailPage/DetailPageCard.tsx
  src/components/detailPage/DetailPageParticipation.tsx
  src/components/main/CardSection.tsx
  src/components/main/TabSection.tsx
  src/components/mypage/AnswerList.tsx
  src/components/mypage/ProfileContainer.tsx
  src/components/providers/MSWComponent.tsx
  src/components/ui/ContainerInformation.tsx
  src/components/ui/Modal/PanpalModal.tsx
  src/components/ui/Modal/PasswordModal.tsx
  src/components/ui/Modal/PlaceAutoCompleteInput.tsx
  src/components/ui/Modal/ProfileModal.tsx
  src/hooks/queries/useFanFalMutations.ts
  src/hooks/queries/useGetList.ts
  src/hooks/queries/useMyPage.ts
  src/mocks/handlers/auths.ts
  src/utils/apis/clientFetcher.ts
  src/utils/apis/concert.ts
  src/utils/apis/fetchInstance.ts
Labels: refactor, fix

#148 [NO ISSUE] user nav바 마이페이지 이미지 출력 해결
  src/components/mypage/ProfileContainer.tsx
  src/components/ui/Modal/ProfileModal.tsx
  src/components/ui/Nav.tsx
  src/components/ui/ProfileSection.tsx
  src/types/auth.ts
Labels: refactor, fix
